version: '2'

services:
    caliper:
        container_name: caliper
        image: hyperledger/caliper:0.6.1
        command: launch manager
        environment:
        - CALIPER_BIND_SUT=besu:1.4
        - CALIPER_BENCHCONFIG=benchmarks/.../config.yaml
        - CALIPER_NETWORKCONFIG=networks/.../test-network.yaml
        volumes:
        - ../:/hyperledger/caliper/workspace