version: '2'

services:
    caliper:
        container_name: caliper
        image: hyperledger/caliper:0.6.0
        entrypoint: sh compose/run-from-compose.sh
        #command: launch manager
        environment:
        - CALIPER_BIND_SUT=besu:1.4
        - CALIPER_BENCHCONFIG=benchmarks/benchmark1.yaml
        - CALIPER_NETWORKCONFIG=networks/network-config.json
        volumes:
        - ../:/hyperledger/caliper/workspace