services:
  ca-os2:
    container_name: ca-os2
    image: hyperledger/fabric-ca
    command: /bin/bash -c 'fabric-ca-server start -d -b ca-os2-admin:adminpw'
    environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - .:/tmp/hyperledger/fabric-ca-server
    networks:
      - fabric-ca
    ports:
      - 7059:7059

networks:
  fabric-ca: