version: '3.7'

services:

  besu-node-0:
    container_name: besu-node-0
    image: hyperledger/besu:latest
    user: root
    environment:
      BESU_DATA_PATH: /var/lib/besu/data
      BESU_GENESIS_FILE: /var/lib/besu/genesis/genesis.json
      BESU_RPC_HTTP_ENABLED: true
      BESU_RPC_HTTP_API: ADMIN,CLIQUE,DEBUG,EEA,ETH,IBFT,MINER,NET,PERM,PLUGINS,PRIV,QBFT,TRACE,TXPOOL,WEB3
      BESU_HOST_ALLOWLIST: "*"
      BESU_RPC_HTTP_CORS_ORIGINS: "all"
      BESU_MIN_GAS_PRICE: 0
      # PORTS
      BESU_RPC_HTTP_PORT: 8500
      BESU_P2P_PORT: 30300
      #BESU_RPC_WS_PORT: 15100
    volumes:
      - ../cryptogen/node0/data:/var/lib/besu/data
      - ../genesis:/var/lib/besu/genesis
    ports:
      - 8500:8500
      - 30300:30300
      #- 15100:15100
    networks:
      besu_network:
    restart: always

networks:
  besu_network:
    external: true